apps/usuario/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from apps.usuario.views import index, UsuarioList, UsuarioCreate, UsuarioUpdate, UsuarioDelete, dashboard, CustomLoginView
from django.contrib.auth.views import LogoutView

app_name = 'usuario'

urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(next_page='/usuario/login'), name='logout'),
	path('', index, name = 'index'),
    path('dashboard/', dashboard, name = 'dashboard'),
    path('list/', login_required(UsuarioList.as_view()), name= 'usuariolist'),
	path('add/', login_required(UsuarioCreate.as_view()), name = 'usuarioadd'),
	path('edit/<int:pk>/', login_required(UsuarioUpdate.as_view()), name= 'usuarioedit'),
	path('delete/<int:pk>/', login_required(UsuarioDelete.as_view()), name = 'usuariodelete'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout', logout_then_login, name = 'logout'),
    path('configuracion/', include('apps.configuracion.urls', namespace = 'configuracion')),
    path('inventario/', include('apps.inventario.urls', namespace = 'inventario')),
    path('compra/', include('apps.compra.urls', namespace = 'compra')),
    path('venta/', include('apps.venta.urls', namespace = 'venta')),
    path('usuario/', include('apps.usuario.urls', namespace = 'usuario')),
]

apps/usuario/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from apps.configuracion.models import Sucursale

# Create your models here.
class UserProfile(AbstractUser):
    # Campos adicionales según tus necesidades
    CONFIA = 'CONFIA'
    CRECER = 'CRECER'
    NOMBRE_AFP_CHOICES = (
		(CONFIA, 'CONFIA'),
		(CRECER, 'CRECER')
	)
    MAMA = 'MAMA'
    PAPA = 'PAPA'
    HERMANO = 'HERMANO'
    HERMANA = 'HERMANA'
    ESPOSA = 'ESPOSA'
    ESPOSO = 'ESPOSO'
    HIJO = 'HIJO'
    HIJA = 'HIJA'
    ABUELA = 'ABUELA'
    ABUELO = 'ABUELO'
    TIO = 'TIO'
    TIA = 'TIA'
    AMIGO = 'AMIGO'
    VECINO = 'VECINO'
    PARENTEZCO_CHOICES = (
		(MAMA, 'MAMA'),
		(PAPA, 'PAPA'),
        (HERMANO, 'HERMANO'),
		(HERMANA, 'HERMANA'),
        (ESPOSA, 'ESPOSA'),
        (ESPOSO, 'ESPOSO'),
        (HIJO, 'HIJO'),
        (HIJA, 'HIJA'),
        (ABUELA, 'ABUELA'),
        (ABUELO, 'ABUELO'),
        (TIO, 'TIO'),
        (TIA, 'TIA'),
        (AMIGO, 'AMIGO'),
        (VECINO, 'VECINO')
	)
    PRIMERCICLO = 'PRIMER CICLO'
    SEGUNDOCICLO = 'SEGUNDO CICLO'
    TERCERCICLO = 'TERCER CICLO'
    BACHILLERATO = 'BACHILLERATO'
    TECNICO = 'TECNICO'
    UNIVERSITARIO = 'UNIVERSITARIO'
    ESTUDIOS_CHOICES = (
        (PRIMERCICLO, 'PRIMER CICLO'),
        (SEGUNDOCICLO, 'SEGUNDO CICLO'),
        (TERCERCICLO, 'TERCER CICLO'),
        (BACHILLERATO, 'BACHILLERATO'),
        (TECNICO, 'TECNICO'),
        (UNIVERSITARIO, 'UNIVERSITARIO'),
    )

    dui = models.CharField(null=True, blank=True, max_length=10)
    nit = models.CharField(null=True, blank=True, max_length=20)
    nomafp = models.CharField(null=True, blank=True, max_length=20, choices = NOMBRE_AFP_CHOICES)
    numafp = models.CharField(null=True, blank=True, max_length=20)    
    isss = models.CharField(null=True, blank=True, max_length=20)
    antecedente = models.BooleanField(null=True, blank=True, default=False)
    solvencia = models.BooleanField(null=True, blank=True)
    vacunaCOVID = models.BooleanField(null=True, blank=True)    
    nombrebanco = models.CharField(null=True, blank=True, max_length=100)
    cuentabanco = models.CharField(null=True, blank=True, max_length=100)
    instituciondisc = models.CharField(null=True, blank=True, max_length=75)
    discapacidad = models.BooleanField(null=True, blank=True)
    direccion = models.CharField(null=True, blank=True, max_length=150)
    telefono = models.CharField(null=True, blank=True, max_length=12)
    celular = models.CharField(null=True, blank=True, max_length=12)
    nomemergencia = models.CharField(null=True, blank=True, max_length=100)
    parenemergencia = models.CharField(null=True, blank=True, max_length=10, choices = PARENTEZCO_CHOICES)
    telemergencia = models.CharField(null=True, blank=True, max_length=12)
    estudios = models.CharField(null=True, blank=True, max_length=20, choices = ESTUDIOS_CHOICES)
    curriculum = models.FileField(upload_to='curriculums', null=True, blank=True)
    email = models.EmailField(null=True, blank=True, max_length=50)
    cargo = models.CharField(null=True, blank=True, max_length=50)
    sexo = models.CharField(null=True, blank=True, max_length=10)
    fecha_in =  models.DateField(null=True, blank=True)
    fecha_exp = models.DateField(null=True, blank=True)
    foto = models.ImageField(upload_to='empleados', null = True, blank=True)
    salario = models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=2)
    viaticos = models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=2)
    cafeteria = models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=2)
    comision = models.DecimalField(null=True, blank=True, max_digits=6, decimal_places=2)
    wallet = models.BooleanField(null=True, blank=True)
    sucursal = models.ForeignKey(Sucursale, on_delete=models.SET_NULL, null=True, blank=True)
    createdate = models.DateTimeField(null=True, blank=True, auto_now_add=True)
    lastupdate = models.DateTimeField(null=True, blank=True, auto_now=True)
    
    def __str__(self):
        return str(self.first_name)

apps/usuario/forms.py
from django import forms
from django.forms import fields, widgets
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from apps.usuario.models import UserProfile
from bootstrap_modal_forms.forms import BSModalModelForm
from django.contrib.auth.forms import AuthenticationForm
from apps.configuracion.models import Sucursale


class CustomAuthenticationForm(AuthenticationForm):
    sucursal = forms.ModelChoiceField(queryset=Sucursale.objects.all(), empty_label=None)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Usuario'})
        self.fields['password'].widget.attrs.update({'class': 'form-control', 'placeholder': 'Contraseña'})
        self.fields['sucursal'].widget.attrs.update({'class': 'form-control'})


class RegistroForm(UserCreationForm, BSModalModelForm):
    
    class Meta:
        model = UserProfile
        fields = [
			'username',
			'first_name',
			'last_name',
			'password1',
			'password2',
			'email',
			'is_active',
			'is_superuser',
   			'is_staff',
			'dui',
			'nit',
			'nomafp',
			'numafp',
			'isss',
			'antecedente',
			'solvencia',
			'vacunaCOVID',
   			'nombrebanco',
			'cuentabanco',
			'instituciondisc',
			'discapacidad',
			'direccion',
			'telefono',
			'celular',
			'nomemergencia',
			'parenemergencia',
			'telemergencia',
			'estudios',
			'curriculum',
			'cargo',
			'sexo',
			'fecha_in',
			'fecha_exp',
			'foto',
			'salario',
			'viaticos',
			'cafeteria',
			'comision',
			'wallet',
			'sucursal',
		]
        labels = {
   
			'username' : 'Nombre de Usuario',
			'first_name' : 'Nombres',
			'last_name' : 'Apellidos',
			'password1' : 'Contraseña',
			'password2' : 'Repita Contraseña',
			'email' : 'Email',
			'is_active' : 'Activo',
			'is_superuser' : 'Super Usuario',
   			'is_staff' : 'Staff',
			'dui' : 'DUI',
			'nit' : 'NIT',
			'nomafp' : 'Nombre AFP',
			'numafp' : 'Numero AFP',
			'isss' : 'ISSS',
			'antecedente' : 'Antecedentes',
			'solvencia' : 'Solvencia',
			'vacunaCOVID' : 'COVID',
			'nombrebanco' : 'Nombre Banco',
			'cuentabanco' : 'Numero de Cuenta',
			'instituciondisc' : 'Institución Discapacitado',
			'discapacidad' : 'Discapacidad',
			'direccion' : 'Direccion',
			'telefono' : 'Telefono',
			'celular' : 'Celular',
			'nomemergencia' : 'Nombre Emergencia',
			'parenemergencia' : 'Parentezco Emergencia',
			'telemergencia' : 'Telefono Emergencia',
			'estudios' : 'Estudios',
			'curriculum' : 'Curriculum',
			'cargo' : 'Cargo',
			'sexo' : 'Sexo',
			'fecha_in' : 'Fecha Ingreso',
			'fecha_exp' : 'Fecha Despido',
			'foto' : 'Foto',
			'salario' : 'Salario',
			'viaticos' : 'Viaticos',
			'cafeteria' : 'Cafeteria',
			'comision' : 'Comision',
			'wallet' : 'Wallet',
			'sucursal' : 'Sucursal',
		}
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control','placeholder': 'Usuario'}),
            'first_name': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombres'}),
            'last_name': forms.TextInput(attrs={'class':'form-control','placeholder': 'Apellidos'}),
            'email' : forms.EmailInput(attrs={'class':'form-control','placeholder': 'Email'}),
			'is_active' : forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
			'is_superuser' : forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
   			'is_staff' : forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'dui': forms.TextInput(attrs={'class':'form-control','placeholder': 'DUI'}),
            'nit': forms.TextInput(attrs={'class':'form-control','placeholder': 'NIT'}),
            'nomafp': forms.Select(attrs={'class':'form-control','placeholder': 'Nombre AFP'}),
            'numafp': forms.TextInput(attrs={'class':'form-control','placeholder': 'Numero AFP'}),
            'isss': forms.TextInput(attrs={'class':'form-control','placeholder': 'Numero ISSS'}),
            'antecedente': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'solvencia': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'vacunaCOVID': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'nombrebanco' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Banco de Banco'}),
            'cuentabanco' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Cuenta de Banco'}),
            'instituciondisc': forms.TextInput(attrs={'class':'form-control','placeholder': 'Institución que Discapacita'}),
            'discapacidad': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'direccion': forms.TextInput(attrs={'class':'form-control','placeholder': 'Direccion'}),
            'telefono': forms.TextInput(attrs={'class':'form-control','placeholder': 'Telefono'}),
            'celular': forms.TextInput(attrs={'class':'form-control','placeholder': 'Celular'}),
            'nomemergencia': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre a llamar en Emergencia'}),
            'parenemergencia': forms.Select(attrs={'class':'form-control','placeholder': 'Parentezco'}),
            'telemergencia': forms.TextInput(attrs={'class':'form-control','placeholder': 'Numero en caso de Emergencia'}),
            'estudios': forms.Select(attrs={'class':'form-control','placeholder': 'Estudios Realizados'}),
            'curriculum': forms.FileInput(attrs={'class':'form-control','placeholder': 'Curriculum'}),
            'cargo': forms.TextInput(attrs={'class':'form-control','placeholder': 'Cargo'}),
            'sexo': forms.TextInput(attrs={'class':'form-control','placeholder': 'Sexo'}),
            'fecha_in': forms.TextInput(attrs={'class':'form-control datetimepicker-input', 'data-target':"#fechaentrada",'placeholder': 'Fecha Ingreso'}),
            'fecha_exp': forms.TextInput(attrs={'class':'form-control datetimepicker-input', 'data-target':"#fechaexp",'placeholder': 'Fecha Expiración'}),
            'foto': forms.FileInput(attrs={'class':'custom-file-input', 'id':'foto', 'name': 'foto','placeholder': 'Seleccione el archivo'}),
            'salario': forms.NumberInput(attrs={'class':'form-control','placeholder': 'Salario'}),
            'viaticos': forms.NumberInput(attrs={'class':'form-control','placeholder': 'Viaticos'}),
            'cafeteria': forms.NumberInput(attrs={'class':'form-control','placeholder': 'Cafetería'}),
            'comision': forms.NumberInput(attrs={'class':'form-control','placeholder': 'Comisión'}),
            'wallet': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'sucursal': forms.Select(attrs={'class':'form-control','placeholder': 'Sucursal'}),
        }
  

apps/usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.models import User
from apps.usuario.models import UserProfile
from apps.usuario.forms import RegistroForm, CustomAuthenticationForm
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalReadView, BSModalDeleteView
from django.views.generic import ListView
from django.contrib.auth.views import LoginView
from django.urls import reverse_lazy



# Create your views here.
class CustomLoginView(LoginView):
    template_name = 'usuario/login.html'
    form_class = CustomAuthenticationForm

    def form_valid(self, form):
        # Guarda la sucursal seleccionada en la sesión del usuario
        self.request.session['sucursal'] = form.cleaned_data['sucursal'].id
        return super().form_valid(form)

    def get_success_url(self):
        return reverse_lazy('usuario:index')  # Cambia esto a la URL deseada después del inicio de sesión


def index(request):
	return render(request, 'usuario/index.html')

def dashboard(request):
	return render(request, 'usuario/dashboard.html')

class UsuarioList(ListView):
	model = UserProfile
	template_name = 'usuario/usuariolist.html'

class UsuarioCreate(BSModalCreateView):
    model = UserProfile
    form_class = RegistroForm    
    template_name = "usuario/usuarioadd.html"
    success_message = 'Hecho! Usuario Creado Correctamente.'
    success_url = reverse_lazy('usuario:usuariolist')

class UsuarioUpdate(BSModalUpdateView):
    model = UserProfile
    form_class = RegistroForm
    template_name = 'usuario/usuarioedit.html'
    success_message = 'Hecho! Usuario Actualizado Correctamente.'
    success_url = reverse_lazy('usuario:usuariolist')
    
    def form_valid(self, form):
        # Obtén el usuario existente
        user = get_object_or_404(UserProfile, pk=self.kwargs['pk'])
        
        # Actualiza los campos del usuario con los datos del formulario
        user.username = form.cleaned_data['username']
        user.first_name = form.cleaned_data['first_name']
        user.last_name = form.cleaned_data['last_name']
        user.password1= form.cleaned_data['password1']
        user.password2= form.cleaned_data['password2']
        user.email = form.cleaned_data['email']
        user.is_active = form.cleaned_data['is_active']
        user.is_superuser = form.cleaned_data['is_superuser']
        user.is_staff = form.cleaned_data['is_staff']
        user.dui = form.cleaned_data['dui']
        user.nit = form.cleaned_data['nit']
        user.nomafp = form.cleaned_data['nomafp']
        user.numafp = form.cleaned_data['numafp']
        user.isss = form.cleaned_data['isss']
        user.antecedente = form.cleaned_data['antecedente']
        user.solvencia = form.cleaned_data['solvencia']
        user.vacunaCOVID = form.cleaned_data['vacunaCOVID']
        user.nombrebanco = form.cleaned_data['nombrebanco']
        user.cuentabanco = form.cleaned_data['cuentabanco']
        user.instituciondisc = form.cleaned_data['instituciondisc']
        user.discapacidad = form.cleaned_data['discapacidad']
        user.direccion = form.cleaned_data['direccion']
        user.telefono = form.cleaned_data['telefono']
        user.celular = form.cleaned_data['celular']
        user.nomemergencia = form.cleaned_data['nomemergencia']
        user.parenemergencia = form.cleaned_data['parenemergencia']
        user.telemergencia = form.cleaned_data['telemergencia']
        user.estudios = form.cleaned_data['estudios']
        user.curriculum = form.cleaned_data['curriculum']
        user.cargo = form.cleaned_data['cargo']
        user.sexo = form.cleaned_data['sexo']
        user.fecha_in = form.cleaned_data['fecha_in']
        user.fecha_exp = form.cleaned_data['fecha_exp']
        user.foto = form.cleaned_data['foto']
        user.salario = form.cleaned_data['salario']
        user.viaticos = form.cleaned_data['viaticos']
        user.cafeteria = form.cleaned_data['cafeteria']
        user.comision = form.cleaned_data['comision']
        user.wallet = form.cleaned_data['wallet']
        user.sucursal = form.cleaned_data['sucursal']
        
        # Guarda el usuario actualizado
        user.save()

        return super().form_valid(form)

class UsuarioDelete(BSModalDeleteView):
    model = UserProfile
    template_name = 'usuario/usuariodelete.html'
    success_message = 'Hecho! Usuario Eliminado Correctamente.'
    success_url = reverse_lazy('usuario:usuariolist')

templates/usuario/index.html
{% extends 'base/base.html' %}

{% block title %}
ControlTotal | Bienvenido
{% endblock %}

{% block content %}
<div id="content">
	<div class="container-fluid">
		<div class="row-fluid">
			<br><br><br><br><br><br><br><br><br>
	      	<div class="span12">
	      		<h5 align="center">Bienvenido al Sistema de Control de Inventario y Facturación <b>Control</b>Total v1.0</h5>
			</div>
			<div align="center">
				<p><font size="1">El software de este sitio web está protegido por las Leyes de Propiedad Intelectual. Queda prohibida la copia parcial o total de su contenido, incluidos los logos y nombres registrados como GlobalTech®. <br />
        		Todos los Derechos Reservados Globaltech®  2010 - Número de Registro 3532017 Versión 1.0</font></p>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/usuario/usuarioadd.html
<form method="post" action="">
    {% csrf_token %}
  
    <div class="modal-header">
        <h5 class="modal-title">Crear Nuevo Usuario</h5> 
        <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      
    </div>
  
    <div class="modal-body">     
      {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% if field.name == 'password1' or field.name == 'password2' %}
            <input type="password" name="{{ field.name }}" class="form-control" placeholder="{{ field.label }}">
          {% else %}
            {{ field }}
          {% endif %}
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      <button type="submit" class="btn btn-primary">Crear</button>
    </div>
  
</form>

{% block scriptbottom %}
<script>
  $(function() {
    $('#id_is_active').bootstrapToggle();
    $('#id_is_superuser').bootstrapToggle();
    $('#id_is_staff').bootstrapToggle();
    $('#id_antecedente').bootstrapToggle();
    $('#id_solvencia').bootstrapToggle();
    $('#id_vacunaCOVID').bootstrapToggle();
    $('#id_discapacidad').bootstrapToggle();
    $('#id_wallet').bootstrapToggle();
  })
</script>
{% endblock %}

templates/usuario/usuariodelete.html
<form method="post" class="form-horizontal">
	{% csrf_token %}

	<div class="modal-header">
		<h3 class="modal-title">Eliminar Usuario</h3>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	  </div>
	
	  <div class="modal-body">
		<p>Desea Eliminar el Registro de 
		  <strong>{{ object.first_name }} {{ object.last_name }}</strong>?</p>
	  </div>
	
	  <div class="modal-footer">
		<button type="submit" class="btn btn-danger">Eliminar</button>
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
	  </div>

</form>	          			            		
	          		

templates/usuario/usuarioedit.html
<form method="post" action="">
    {% csrf_token %}
  
    <div class="modal-header">
        <h5 class="modal-title">Actualizar Usuario</h5> 

		<button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
			<span aria-hidden="true">&times;</span>
		</button>
      
    </div>
  
    <div class="modal-body">
      {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {% if field.name == 'password1' or field.name == 'password2' %}
            <input type="password" name="{{ field.name }}" class="form-control" placeholder="{{ field.label }}">
          {% else %}
            {{ field }}
          {% endif %}
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      <button type="submit" class="btn btn-primary">Actualizar</button>
    </div>
  
</form>

{% block scriptbottom %}
<script>
  $(function() {
    $('#id_is_active').bootstrapToggle();
    $('#id_is_superuser').bootstrapToggle();
    $('#id_is_staff').bootstrapToggle();
    $('#id_antecedente').bootstrapToggle();
    $('#id_solvencia').bootstrapToggle();
    $('#id_vacunaCOVID').bootstrapToggle();
    $('#id_discapacidad').bootstrapToggle();
    $('#id_wallet').bootstrapToggle();
  })
</script>
{% endblock %}

templates/usuario/usuariolist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Usuarios</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Usuarios en el Sistema SnackCash&reg</h3>
						<button id="create-user" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Usuario</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="user-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
	                  				<th>Usuario</th>
	                  				<th>Nombre Completo</th>
	                  				<th>Email</th>
	                  				<th>Activo</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for usuario in object_list %}
			                			<tr class="gradeU">
											<td>{{ usuario.id }}</td>
			                  				<td>{{ usuario.username }}</td>
			                  				<td>{{ usuario.first_name }} {{ usuario.last_name }}</td>
			                  				<td>{{ usuario.email }}</td>
			                  				<td>{{ usuario.is_active }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-user bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'usuario:usuarioedit' usuario.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-user bs-modal btn btn-sm btn-danger" data-form-url="{% url 'usuario:usuariodelete' usuario.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-user").modalForm({
				formURL: "{% url 'usuario:usuarioadd' %}"
			});

			var table = $("#user-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#user-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-user").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-user").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}