apps/compra/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import verificar_inventario, CompraList, CompraCreate, CompraUpdate, CompraDelete, CompraRead, DetalleCompraCreate, DetalleCompraDelete, DetalleCompraList, DetalleCompraUpdate, ProveedoreList, ProveedoreCreate, ProveedoreUpdate, ProveedoreDelete, Sessiones

app_name = 'compra'

urlpatterns = [
    
    path('proveedores/', login_required(ProveedoreList.as_view()), name='proveedorelist'),
    path('proveedores/create/', login_required(ProveedoreCreate.as_view()), name='proveedorecreate'),
    path('proveedores/edit/<int:pk>/', login_required(ProveedoreUpdate.as_view()), name='proveedoreedit'),
    path('proveedores/delete/<int:pk>/', login_required(ProveedoreDelete.as_view()), name='proveedoredelete'),
    
    path('compras/sesiones', Sessiones, name = 'sesiones'),
    path('compras/', login_required(CompraList.as_view()), name='compralist'),
    path('compras/create/', login_required(CompraCreate.as_view()), name='compracreate'),
    path('compras/read/<int:pk>/', login_required(CompraRead.as_view()), name='compraread'),
    path('compras/edit/<int:pk>/', login_required(CompraUpdate.as_view()), name='compraedit'),
    path('compras/delete/<int:pk>/', login_required(CompraDelete.as_view()), name='compradelete'),
    
    path('detallecompras/', login_required(DetalleCompraList.as_view()), name='detallecompralist'),
    path('detallecompras/create/<int:compra_id>/', login_required(DetalleCompraCreate.as_view()), name='detallecompracreate'),
    path('detallecompras/edit/<int:pk>/<int:compra_id>/', login_required(DetalleCompraUpdate.as_view()), name='detallecompraedit'),
    path('detallecompras/delete/<int:pk>/<int:compra_id>/', login_required(DetalleCompraDelete.as_view()), name='detallecompradelete'),
    path('detallecompras/verificar-inventario/', verificar_inventario, name='verificar_inventario'),
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout', logout_then_login, name = 'logout'),
    path('configuracion/', include('apps.configuracion.urls', namespace = 'configuracion')),
    path('inventario/', include('apps.inventario.urls', namespace = 'inventario')),
    path('compra/', include('apps.compra.urls', namespace = 'compra')),
    path('venta/', include('apps.venta.urls', namespace = 'venta')),
    path('usuario/', include('apps.usuario.urls', namespace = 'usuario')),
]

apps/compra/models.py
from email.policy import default
from random import choices
from django.db import models

from apps.inventario.models import Producto

# Create your models here.
class Proveedore(models.Model):
    nombre = models.CharField(max_length=100)
    representante = models.CharField(max_length=150, blank=True, null=True)
    direccion = models.CharField(max_length=255, blank=True, null=True)
    nit = models.CharField(max_length=14, blank=True, null=True)
    iva = models.CharField(max_length=14, blank=True, null=True)
    tel = models.CharField(max_length=45, blank=True, null=True)
    email = models.EmailField(max_length=45, blank=True, null=True)
    descripcion = models.CharField(max_length=255, blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Compra(models.Model):
    
    ESTADO_COMPRA_CHOICES = (
        ('PAGADA', 'Pagada'),
        ('ANULADA', 'Anulada'),
        ('CREDITO 30', 'Crédito 30'),
        ('CREDITO 60', 'Crédito 60'),
        ('CREDITO 90', 'Crédito 90'),
        # Puedes agregar más opciones aquí
    )
    
    factura = models.CharField(max_length=15, blank=True)
    totalcompra = models.DecimalField(max_digits=10, decimal_places=4, blank=True, null=True)
    estado = models.CharField(max_length=10, choices = ESTADO_COMPRA_CHOICES)
    pagocaja = models.BooleanField(default=False)
    bonificacion = models.BooleanField(default=False)
    descripcion = models.TextField(blank=True)
    proveedor = models.ForeignKey(Proveedore, on_delete=models.DO_NOTHING)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.factura + " - " + self.proveedor # type: ignore

class Detallecompra(models.Model):
    cantidad = models.IntegerField()
    preciounitario = models.DecimalField(max_digits=10, decimal_places=4)
    preciototal = models.DecimalField(max_digits=10, decimal_places=4)
    compra = models.ForeignKey(Compra, on_delete=models.DO_NOTHING)
    producto = models.ForeignKey(Producto, on_delete=models.DO_NOTHING)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)

apps/compra/views.py
from django.shortcuts import render, redirect
from .models import Compra, Detallecompra, Proveedore
from apps.configuracion.models import Configuracione
from apps.inventario.models import Inventario, Producto
from .forms import CompraForm, ProveedoreForm, DetalleCompraForm
from django.views.generic import ListView
from django.contrib import messages
from django.urls import reverse_lazy, reverse
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalReadView, BSModalDeleteView

# Create your views here.
class ProveedoreList(ListView):
    model = Proveedore
    template_name = 'compra/proveedorelist.html'
    
class ProveedoreCreate(BSModalCreateView):
    model = Proveedore
    form_class = ProveedoreForm
    template_name = 'compra/proveedoreadd.html'
    success_message = 'Hecho! Proveedor Creado Correctamente.'
    success_url = reverse_lazy('compra:proveedorelist')
    
class ProveedoreUpdate(BSModalUpdateView):
    model = Proveedore
    form_class = ProveedoreForm
    template_name = 'compra/proveedoreedit.html'
    success_message = 'Hecho! Proveedor Actualizado Correctamente.'
    success_url = reverse_lazy('compra:proveedorelist')

class ProveedoreDelete(BSModalDeleteView):
    model = Proveedore
    template_name = 'compra/proveedoredelete.html'
    success_message = 'Hecho! Proveedor Eliminado Correctamente.'
    success_url = reverse_lazy('compra:proveedorelist')
    
##########################################################################################

class CompraList(ListView):
    model = Compra
    template_name = 'compra/compralist.html'
    
class CompraCreate(BSModalCreateView):
    model = Compra
    form_class = CompraForm
    template_name = 'compra/compraadd.html'
    success_message = 'Hecho! Compra Creada Correctamente.'
    
    def get_success_url(self):
        # Obtener el último objeto Compra creado
        ultima_compra = Compra.objects.latest('id')
        # Obtener el id de la última compra
        id_compra = ultima_compra.id # type: ignore
        # Redirigir a la vista de detalle de la última compra
        return reverse('compra:compraread', kwargs={'pk': id_compra})
    
class CompraRead(BSModalReadView):
    model = Compra
    template_name = 'compra/compradetalle.html'
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['detallecompras'] = Detallecompra.objects.filter(compra=self.object) # type: ignore
        return context

class CompraUpdate(BSModalUpdateView):
    model = Compra
    form_class = CompraForm
    template_name = 'compra/compraedit.html'
    success_message = 'Hecho! Compra Actualizada Correctamente.'
    success_url = reverse_lazy('compra:compralist')

class CompraDelete(BSModalDeleteView):
    model = Compra
    template_name = 'compra/compradelete.html'
    success_message = 'Hecho! Compra Eliminada Correctamente.'
    success_url = reverse_lazy('compra:compralist')
    
############################################################################################
    
class DetalleCompraList(ListView):
    model = Detallecompra
    template_name = 'compra/detallecompralist.html'
    
class DetalleCompraCreate(BSModalCreateView):
    model = Detallecompra
    form_class = DetalleCompraForm
    template_name = 'compra/detallecompraadd.html'
    success_message = 'Hecho! Detalle Creado Correctamente.'
    
    def get_success_url(self):
        return reverse('compra:compraread', kwargs={'pk': self.kwargs.get('compra_id')})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['compra_id'] = self.kwargs.get('compra_id')
        
        # Obtener la sucursal del usuario desde la sesión (asegúrate de tenerla guardada en la sesión)
        sucursal_id = self.request.session.get('sucursal')
        # Obtener configuración de la sucursal
        configuracion = get_object_or_404(Configuracione, sucursal_id=sucursal_id)
        if configuracion.utilidadactive is True:
            context['utilidadactive'] = configuracion.utilidadactive
        else:
            context['utilidadactive'] = False        
        
        # Obtener los valores de stock mínimo y máximo del producto
        producto_id = self.request.GET.get('producto')
        inventario = Inventario.objects.filter(producto_id=producto_id).first()
        if inventario:
            context['stockminimo'] = inventario.stockminimo
            context['stockmaximo'] = inventario.stockmaximo
            
        return context

    def form_valid(self, form):
        compra_id = self.kwargs.get('compra_id')
        producto_id = form.cleaned_data['producto'].id
        cantidad = form.cleaned_data['cantidad']
        preciototal = form.cleaned_data['preciototal']

        # Verificar si el producto ya existe en la compra
        if Detallecompra.objects.filter(compra_id=compra_id, producto_id=producto_id).exists():
            messages.error(self.request, 'El producto ya está en la compra.')
            return redirect('compra:compraread', pk=compra_id)

        # Si el producto no existe en la compra, proceder con la creación del detalle
        form.instance.compra_id = compra_id
        response = super().form_valid(form)
        
        # Obtener la sucursal del usuario desde la sesión (asegúrate de tenerla guardada en la sesión)
        sucursal_id = self.request.session.get('sucursal')
        
        # Obtener configuración de la sucursal
        configuracion = get_object_or_404(Configuracione, sucursal_id=sucursal_id)

        # Obtener detalles del producto
        producto = get_object_or_404(Producto, pk=producto_id)

        # Calcular cantidadtotal
        cantidadtotal = cantidad * producto.cantidadcontenedor

        # Calcular preciocompra
        preciocompra = preciototal / cantidadtotal

        # Calcular iva y utilidad
        iva = (preciocompra * configuracion.iva) / 100
        if configuracion.utilidadactive is True:
            utilidad = (preciocompra * configuracion.utilidad) / 100
            # Calcular precioventa
            precioventa = preciocompra + utilidad + iva
        else:            
            # Calcular precioventa
            precioventa = form.cleaned_data['precioventa']
            utilidad = precioventa - (preciocompra + iva)        
        
        # Crear o actualizar el objeto Inventario
        inventario, created = Inventario.objects.get_or_create(
            producto_id=producto_id,
            sucursal_id=sucursal_id,
            defaults={
                'stock': cantidadtotal,
                'preciocompra': preciocompra,
                'iva': iva,
                'utilidad': utilidad,
                'precioventa': precioventa,
                'stockminimo': form.cleaned_data['stockminimo'],
                'stockmaximo': form.cleaned_data['stockmaximo'],
                'usercreate': self.request.user.username,  # Usuario que crea el registro # type: ignore
                'usermodify': self.request.user.username   # Usuario que modifica el registro # type: ignore
            }
        )
        
        if not created:
            # Si ya existe el objeto Inventario, actualiza el stock sumando la cantidad del detalle
            inventario.stock += cantidad
            inventario.stockminimo = form.cleaned_data['stockminimo']
            inventario.stockmaximo = form.cleaned_data['stockmaximo']
            inventario.save()
        
        return response

class DetalleCompraUpdate(BSModalUpdateView):
    model = Detallecompra
    form_class = DetalleCompraForm
    template_name = 'compra/detallecompraedit.html'
    success_message = 'Hecho! Detalle Actualizado Correctamente.'
    
    def get_object(self, queryset=None):
        compra_id = self.kwargs.get('compra_id')
        pk = self.kwargs.get('pk')
        return get_object_or_404(Detallecompra, pk=pk, compra_id=compra_id)
    
    def get_success_url(self):
        return reverse('compra:compraread', kwargs={'pk': self.kwargs.get('compra_id')})

    def form_valid(self, form):
        detallecompra = self.get_object()

        # Verificar si la cantidad es 0
        cantidad = form.cleaned_data['cantidad']
        if cantidad == 0:
            messages.error(self.request, 'La cantidad del producto no puede ser 0.')
            return redirect('compra:compraread', pk=self.kwargs.get('compra_id'))

        # Obtener la diferencia entre la cantidad anterior y la cantidad actual
        cantidad_anterior = detallecompra.cantidad 
        diferencia_cantidad = cantidad - cantidad_anterior

        # Obtener el producto y la sucursal
        producto_id = form.cleaned_data['producto'].id
        sucursal_id = self.request.session.get('sucursal')

        # Actualizar el inventario
        try:
            inventario = Inventario.objects.get(producto_id=producto_id, sucursal_id=sucursal_id)
            inventario.stock += diferencia_cantidad
            inventario.save()
        except Inventario.DoesNotExist:
            pass  # Manejar la excepción si no existe el registro en inventario

        return super().form_valid(form)

class DetalleCompraDelete(BSModalDeleteView):
    model = Detallecompra
    template_name = 'compra/detallecompradelete.html'
    success_message = 'Hecho! Compra Eliminada Correctamente.'
    
    def get_success_url(self):
        return reverse('compra:compraread', kwargs={'pk': self.kwargs.get('compra_id')})
    
    def form_valid(self, form):
        detallecompra = self.get_object()
        
        if detallecompra is None:
            # Manejar el caso en el que el objeto no se encuentra
            print("Objeto Detallecompra no encontrado")
        else:
            # Procesar el objeto detallecompra
            # print(f"ID de Detallecompra: {detallecompra.id}")

templates/compra/compraadd.html
<form method="post" action="">
    {% csrf_token %}
  
    <div class="modal-header">
        <h5 class="modal-title">Crear Nueva Compra</h5> 
        <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      
    </div>
  
    <div class="modal-body">
      {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}      
    </div>
  
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      <button type="submit" class="btn btn-primary">Crear</button>
    </div>
  
</form>

templates/compra/compradetalle.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}

<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Compra de Productos en el Sistema SnackCash&reg</h3>
						<button id="create-detalle" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Ingresar Productos Compra</button>
                        <br><hr/><br>
						<div class="row">
                            <div class="col-md-3">
                                <p>Factura</p>
                                <p>Proveedor</p>
                                <p>Descripcion</p>
                                <p>Pago/Caja</p>
                                <p>Bonificación</p>
                                <p>Tot/Compra</p>
                                <p>Estado</p>
                            </div>
							<div class="col-md-9">
                                <p>{{ compra.factura }}</p>
                                <p>{{ compra.proveedor }}</p>
                                <p>{{ compra.descripcion }}</p>
                                <p>{{ compra.pagocaja }}</p>
                                <p>{{ compra.bonificacion }}</p>
                                <p>{{ compra.totalcompra }}</p>
                                <p>
									<span class="right badge badge-success">{{ compra.estado }}</span>
								</p>
                            </div>
                        </div>
                    </div>
                    		          		
	          		<div class="card-body">
	            		<table id="detalle-table" class="table table-bordered table-striped" style="width:100%">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Producto</th>
									<th>Cantidad</th>
									<th>Precio/Uni</th>
	                  				<th>Precio/Total</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>	 
								{% for detallecompra in detallecompras %}
									<tr class="gradeU">
										<td>{{ detallecompra.id }}</td>
										<td>{{ detallecompra.producto }}</td>
										<td>{{ detallecompra.cantidad }}</td>
										<td>{{ detallecompra.preciounitario }}</td>
										<td>{{ detallecompra.preciototal }}</td>
										<td>												
											<button type="button" class="edit-detallecompra bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'compra:detallecompraedit' detallecompra.id compra.id %}">
												<span class="fa fa-user-edit"></span>
											</button>			                  					
											<button type="button" class="delete-detallecompra bs-modal btn btn-sm btn-danger" data-form-url="{% url 'compra:detallecompradelete' detallecompra.id compra.id %}">
												<span class="fa fa-trash"></span>
											</button>									
										</td>
									</tr>
								{% endfor %}		
	              			</tbody>
							<tfoot>
								<tr>
									<th colspan="4" style="text-align:right">Total:</th>
									<th></th>
									<th></th>
								</tr>
							</tfoot>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}
	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-detalle").modalForm({
				formURL: "{% url 'compra:detallecompracreate' compra.id %}"
			});

			var table = $("#detalle-table").DataTable({				
				language: {
					"decimal": ".",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},

				"ordering": true,
				"info": true,
				"responsive": true,
				"lengthChange": true,
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#detalle-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-detallecompra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-detallecompra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
{% endblock %}

templates/compra/compralist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Compras</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Compra de Productos en el Sistema SnackCash&reg</h3>
						<button id="create-compra" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Compra</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="compra-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Factura</th>
									<th>Proveedor</th>
									<th>Descripción</th>
	                  				<th>Pago/Caja</th>
									<th>Bonificación</th>
									<th>Tot/Compra</th>
									<th>Estado</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for compra in object_list %}
			                			<tr class="gradeU">
											<td>{{ compra.id }}</td>
			                  				<td>
												<a href="{% url 'compra:compraread' compra.id%}">{{ compra.factura }}</a>
											</td>
											<td>{{ compra.proveedor }}</td>
											<td>{{ compra.descripcion }}</td>
											<td>{{ compra.pagocaja }}</td>
			                  				<td>{{ compra.bonificacion }}</td>
											<td>{{ compra.totalcompra }}</td>
											<td>{{ compra.estado }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-compra bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'compra:compraedit' compra.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-compra bs-modal btn btn-sm btn-danger" data-form-url="{% url 'compra:compradelete' compra.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}
	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-compra").modalForm({
				formURL: "{% url 'compra:compracreate' %}"
			});

			var table = $("#compra-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#compra-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-compra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-compra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>		
{% endblock %}

templates/compra/detallecompralist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Compras</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Compra de Productos en el Sistema SnackCash&reg</h3>
						<button id="create-compra" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Compra</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="compra-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Factura</th>
									<th>Proveedor</th>
									<th>Descripción</th>
	                  				<th>Pago/Caja</th>
									<th>Bonificación</th>
									<th>Tot/Compra</th>
									<th>Estado</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for compra in object_list %}
			                			<tr class="gradeU">
											<td>{{ compra.id }}</td>
			                  				<td>{{ compra.factura }}</td>
											<td>{{ compra.proveedor }}</td>
											<td>{{ compra.descripcion }}</td>
											<td>{{ compra.pagocaja }}</td>
			                  				<td>{{ compra.bonificacion }}</td>
											<td>{{ compra.totalcompra }}</td>
											<td>{{ compra.estado }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-compra bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'compra:compraedit' compra.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-compra bs-modal btn btn-sm btn-danger" data-form-url="{% url 'compra:compradelete' compra.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-compra").modalForm({
				formURL: "{% url 'compra:compracreate' %}"
			});

			var table = $("#compra-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#compra-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-compra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-compra").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}

templates/compra/sessiones.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Variables de Sesión</title>
</head>
<body>
    <h1>Variables de Sesión</h1>
    <ul>
        {% for key in session_data %}
            <li>{{ key }}: {{ value }}</li>
        {% endfor %}
    </ul>
</body>
</html>