apps/configuracion/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import EmpresaList, EmpresaCreate, EmpresaUpdate, EmpresaDelete, SucursaleList, \
    SucursaleCreate, SucursaleUpdate, SucursaleDelete , ConfiguracioneList, ConfiguracioneCreate, \
    ConfiguracioneUpdate, ConfiguracioneDelete, CorrelativoFactList, CorrelativoFactCreate, \
    CorrelativoFactUpdate, CorrelativoFactDelete

app_name = 'configuracion'


urlpatterns = [
    path('empresas/', login_required(EmpresaList.as_view()), name='empresalist'),
    path('empresas/create/', login_required(EmpresaCreate.as_view()), name='empresacreate'),
    path('empresas/edit/<int:pk>/', login_required(EmpresaUpdate.as_view()), name='empresaedit'),
    path('empresas/delete/<int:pk>/', login_required(EmpresaDelete.as_view()), name='empresadelete'),
    
    path('sucursales/', login_required(SucursaleList.as_view()), name='sucursallist'),
    path('sucursales/create/', login_required(SucursaleCreate.as_view()), name='sucursalcreate'),
    path('sucursales/edit/<int:pk>/', login_required(SucursaleUpdate.as_view()), name='sucursaledit'),
    path('sucursales/delete/<int:pk>/', login_required(SucursaleDelete.as_view()), name='sucursaldelete'),
    
    path('configuraciones/', login_required(ConfiguracioneList.as_view()), name='configuracionlist'),
    path('configuraciones/create/', login_required(ConfiguracioneCreate.as_view()), name='configuracioncreate'),
    path('configuraciones/edit/<int:pk>/', login_required(ConfiguracioneUpdate.as_view()), name='configuracionedit'),
    path('configuraciones/delete/<int:pk>/', login_required(ConfiguracioneDelete.as_view()), name='configuraciondelete'),
    
    path('correlativos/', login_required(CorrelativoFactList.as_view()), name='correlativolist'),
    path('correlativos/create/', login_required(CorrelativoFactCreate.as_view()), name='correlativocreate'),
    path('correlativos/edit/<int:pk>/', login_required(CorrelativoFactUpdate.as_view()), name='correlativoedit'),
    path('correlativos/delete/<int:pk>/', login_required(CorrelativoFactDelete.as_view()), name='correlativodelete'),

]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout', logout_then_login, name = 'logout'),
    path('configuracion/', include('apps.configuracion.urls', namespace = 'configuracion')),
    path('inventario/', include('apps.inventario.urls', namespace = 'inventario')),
    path('compra/', include('apps.compra.urls', namespace = 'compra')),
    path('venta/', include('apps.venta.urls', namespace = 'venta')),
    path('usuario/', include('apps.usuario.urls', namespace = 'usuario')),
]

apps/configuracion/models.py
from unittest.util import _MAX_LENGTH
from django.db import models

# Create your models here.

class Empresa(models.Model):
    nombre = models.CharField(max_length=255)
    licencia = models.CharField(max_length=255)
    fechaini = models.DateField()
    fechafin = models.DateField()
    logo = models.ImageField(upload_to='empresas/', max_length=200, blank=True, null=True)
    about = models.CharField(max_length=100, blank=True, null=True)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Sucursale(models.Model):
    nombre = models.CharField(max_length=100)
    direccion = models.CharField(max_length=255)
    ipsucursal = models.CharField(max_length=15)
    empresa = models.ForeignKey(Empresa, on_delete=models.DO_NOTHING )
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.nombre

class Configuracione(models.Model):
    utilidadactive = models.BooleanField()
    utilidad = models.IntegerField(blank=True, null=True)
    ivaactive = models.BooleanField()
    iva = models.IntegerField(blank=True, null=True)
    sucursal = models.ForeignKey(Sucursale, on_delete=models.DO_NOTHING)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.sucursal
    
class CorrelativoFact(models.Model):
    
    TICKET = 'TICKET'
    FACTURA = 'FACTURA'
    CREDITO_FISCAL = 'CREDITO FISCAL'
    TIPO_DOCUMENTO_CHOICES = (
		(TICKET, 'TICKET'),
		(FACTURA, 'FACTURA'),
        (CREDITO_FISCAL, 'CREDITO FISCAL')
	)
    correlativoini = models.CharField(max_length=100)
    correlativofin = models.CharField(max_length=100)
    tipodocumento = models.CharField(null=True, blank=True, max_length=15, choices = TIPO_DOCUMENTO_CHOICES)
    numdocumentoasig = models.CharField(max_length=50)
    fechadocumento = models.DateField()
    correlativoact = models.CharField(max_length=50)
    sucursal = models.ForeignKey(Sucursale, on_delete=models.DO_NOTHING)
    creado = models.DateTimeField(auto_now_add=True)
    modificado = models.DateTimeField(auto_now=True)
    usercreate = models.CharField(max_length=20)
    usermodify = models.CharField(max_length=20, blank=True, null=True)
    
    def __str__(self):
        return self.sucursal

apps/configuracion/forms.py
# forms.py
from django import forms
from .models import Empresa, Sucursale, Configuracione, CorrelativoFact
from bootstrap_modal_forms.forms import BSModalModelForm

class EmpresaForm(BSModalModelForm):
    class Meta:
        model = Empresa
        fields = [
			'nombre',
			'licencia',
			'fechaini',
			'fechafin',
			'logo',
			'about',
		]
        labels = {
   
			'nombre' : 'Nombre de Empresa',
			'licencia' : 'Licencia',
			'fechaini' : 'Fecha Inicio',
			'fechafin' : 'Fecha Fin',
			'logo' : 'Logo Empresa',
			'about' : 'Acerca Empresa',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Empresa'}),
            'licencia': forms.TextInput(attrs={'class':'form-control','placeholder': 'Licencia'}),
            'fechaini': forms.TextInput(attrs={'class':'form-control','placeholder': 'Fecha Inicio Licencia'}),
            'fechafin' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Fecha Fin Licencia'}),
            'logo' : forms.ClearableFileInput(attrs={'class':'form-control', 'placeholder': 'Seleccione el Logo de su Empresa'}),
            'about' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Acerca Empresa'}),
        }
        

class SucursaleForm(BSModalModelForm):
    class Meta:
        model = Sucursale
        fields = [
            'empresa',
			'nombre',
			'direccion',
			'ipsucursal',			
		]
        labels = {   
            'empresa' : 'Empresa',
			'nombre' : 'Nombre de Sucursal',
			'direccion' : 'Dirección',
			'ipsucursal' : 'IP Sucursal',			
        }
        widgets = {
            'empresa' : forms.Select(attrs={'class':'form-control','placeholder': 'Empresa'}),
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Sucursal'}),
            'direccion': forms.TextInput(attrs={'class':'form-control','placeholder': 'Dirección'}),
            'ipsucursal': forms.TextInput(attrs={'class':'form-control','placeholder': 'IP Sucursal'}),
        }

class ConfiguracioneForm(BSModalModelForm):
    class Meta:
        model = Configuracione
        fields = [
			'sucursal',
			'utilidadactive',
			'utilidad',
			'ivaactive',
            'iva',
		]
        labels = {   
			'sucursal' : 'Nombre de Sucursal',
			'utilidadactive' : 'Activar Utilidad',
			'utilidad' : 'Porcentaje de Utilidad',
			'ivaactive' : 'Activar IVA',
            'iva' : 'Porcentaje IVA',
        }
        widgets = {
            'sucursal': forms.Select(attrs={'class':'form-control','placeholder': 'Nombre Sucursal'}),
            'utilidadactive': forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'utilidad': forms.TextInput(attrs={'class':'form-control','placeholder': 'Porcentaje Utilidad'}),
            'ivaactive' : forms.CheckboxInput(attrs={'data-toggle':'toggle', 'data-onstyle':'success', 'data-offstyle':'danger'}),
            'iva' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Porcentaje IVA'}),
        }

class CorrelativoFactForm(BSModalModelForm):
    class Meta:
        model = CorrelativoFact
        fields = [
			'sucursal',
			'tipodocumento',
			'correlativoini',
			'correlativofin',
			'numdocumentoasig',
			'fechadocumento',
            'correlativoact',
		]
        labels = {
   
			'sucursal' : 'Nombre de Sucursal',
			'tipodocumento' : 'Tipo Documento',
			'correlativoini' : 'Correlativo Inicio',
			'correlativofin' : 'Correlativo Fin',
			'numdocumentoasig' : 'Numero Docs Asignados',
			'fechadocumento' : 'Fecha Documento',
			'correlativoact' : 'Correlativo Actual',
        }
        widgets = {
            'sucursal': forms.Select(attrs={'class':'form-control','placeholder': 'Nombre Sucursal'}),
            'tipodocumento': forms.Select(attrs={'class':'form-control','placeholder': 'Tipo Documento'}),
            'correlativoini': forms.TextInput(attrs={'class':'form-control','placeholder': 'Inicio Correlativo'}),
            'correlativofin' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Fin Correlativo'}),
            'numdocumentoasig' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Numero Documento Asignación'}),
            'fechadocumento' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Fecha Documento Asignación'}),
            'correlativoact' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Correlativo Actual'}),
        }

apps/configuracion/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Empresa, Sucursale, Configuracione, CorrelativoFact
from .forms import EmpresaForm, SucursaleForm, ConfiguracioneForm, CorrelativoFactForm
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalReadView, BSModalDeleteView
from django.urls import reverse_lazy

# Create your views here.

class EmpresaList(ListView):
    model = Empresa
    template_name = 'configuracion/empresalist.html'

class EmpresaCreate(BSModalCreateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = 'configuracion/empresaadd.html'
    success_message = 'Hecho! Empresa Creada Correctamente.'
    success_url = reverse_lazy('configuracion:empresalist')

class EmpresaUpdate(BSModalUpdateView):
    model = Empresa
    form_class = EmpresaForm
    template_name = 'configuracion/empresaedit.html'
    success_message = 'Hecho! Empresa Actualizada Correctamente.'
    success_url = reverse_lazy('configuracion:empresalist')

class EmpresaDelete(BSModalDeleteView):
    model = Empresa
    template_name = 'configuracion/empresadelete.html'
    success_message = 'Hecho! Empresa Eliminada Correctamente.'
    success_url = reverse_lazy('configuracion:empresalist')
    
#####################################################################################################3

class SucursaleList(ListView):
    model = Sucursale
    template_name = 'configuracion/sucursallist.html'

class SucursaleCreate(BSModalCreateView):
    model = Sucursale
    form_class = SucursaleForm
    template_name = 'configuracion/sucursaladd.html'
    success_message = 'Hecho! Sucursal Creada Correctamente.'
    success_url = reverse_lazy('configuracion:sucursallist')
    
class SucursaleUpdate(BSModalUpdateView):
    model = Sucursale
    form_class = SucursaleForm
    template_name = 'configuracion/sucursaledit.html'
    success_message = 'Hecho! Sucursal Actualizado Correctamente.'
    success_url = reverse_lazy('configuracion:sucursallist')

class SucursaleDelete(BSModalDeleteView):
    model = Sucursale
    template_name = 'configuracion/sucursaldelete.html'
    success_message = 'Hecho! Sucursal Eliminada Correctamente.'
    success_url = reverse_lazy('configuracion:sucursallist')
    
#######################################################################################################

class ConfiguracioneList(ListView):
    model = Configuracione
    template_name = 'configuracion/configuracionlist.html'
    
class ConfiguracioneCreate(BSModalCreateView):
    model = Configuracione
    form_class = ConfiguracioneForm
    template_name = 'configuracion/configuracionadd.html'
    success_message = 'Hecho! Configuración de Sucursal Creada Correctamente.'
    success_url = reverse_lazy('configuracion:configuracionlist')
    
class ConfiguracioneUpdate(BSModalUpdateView):
    model = Configuracione
    form_class = ConfiguracioneForm
    template_name = 'configuracion/configuracionedit.html'
    success_message = 'Hecho! Configuración de Sucursal Actualizada Correctamente.'
    success_url = reverse_lazy('configuracion:configuracionlist')

class ConfiguracioneDelete(BSModalDeleteView):
    model = Configuracione
    template_name = 'configuracion/configuraciondelete.html'
    success_message = 'Hecho! Configuración de Sucursal Eliminada Correctamente.'
    success_url = reverse_lazy('configuracion:configuracionlist')
    
######################################################################################################    

class CorrelativoFactList(ListView):
    model = CorrelativoFact
    template_name = 'configuracion/correlativolist.html'
    
class CorrelativoFactCreate(BSModalCreateView):
    model = CorrelativoFact
    form_class = CorrelativoFactForm
    template_name = 'configuracion/correlativoadd.html'
    success_message = 'Hecho! Correlativo de Documentos para la Sucursal Creada Correctamente.'
    success_url = reverse_lazy('configuracion:correlativolist')
    
class CorrelativoFactUpdate(BSModalUpdateView):
    model = CorrelativoFact
    form_class = CorrelativoFactForm
    template_name = 'configuracion/correlativoedit.html'
    success_message = 'Hecho! Correlativo de Documentos para la Sucursal Actualizada Correctamente.'
    success_url = reverse_lazy('configuracion:correlativolist')

class CorrelativoFactDelete(BSModalDeleteView):
    model = CorrelativoFact
    template_name = 'configuracion/correlativodelete.html'
    success_message = 'Hecho! Correlativo de Documentos para la Sucursal Eliminada Correctamente.'
    success_url = reverse_lazy('configuracion:correlativolist')

templates/configuracion/configuracionlist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Configuraciones</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Configuracion de Sucursales en el Sistema SnackCash&reg</h3>
						<button id="create-configuracion" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Configuracion</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="configuracion-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
	                  				<th>Sucursal</th>
	                  				<th>Utilidad Activa</th>
	                  				<th>Porentaje Utilidad</th>
	                  				<th>IVA Activo</th>
	                  				<th>Porentaje IVA</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for configuracion in object_list %}
			                			<tr class="gradeU">
											<td>{{ configuracion.id }}</td>
			                  				<td>{{ configuracion.sucursal }}</td>
			                  				<td>{{ configuracion.utilidadactive }}</td>
											<td>{{ configuracion.utilidad }}</td>
			                  				<td>{{ configuracion.ivaactive }}</td>
			                  				<td>{{ configuracion.iva }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-configuracion bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'configuracion:configuracionedit' configuracion.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-configuracion bs-modal btn btn-sm btn-danger" data-form-url="{% url 'configuracion:configuraciondelete' configuracion.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-configuracion").modalForm({
				formURL: "{% url 'configuracion:configuracioncreate' %}"
			});

			var table = $("#configuracion-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#user-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-configuracion").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-configuracion").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}

templates/configuracion/correlativolist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Correlativos</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Correlativos para Sucursales en el Sistema SnackCash&reg</h3>
						<button id="create-correlativo" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Empresa</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="correlativo-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
	                  				<th>Sucursal</th>
	                  				<th>Tipo documento</th>
	                  				<th>Correlativo Inicial</th>
	                  				<th>Correlativo Final</th>
									<th>Num Docs Asignados</th>
									<th>Fecha Documento</th>
									<th>Correlativo Actual</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for correlativo in object_list %}
			                			<tr class="gradeU">
											<td>{{ correlativo.id }}</td>
			                  				<td>{{ correlativo.sucursal }}</td>
											<td>{{ correlativo.tipodocumento }}</td>
			                  				<td>{{ correlativo.correlativoini }}</td>
			                  				<td>{{ correlativo.correlativofin }}</td>
			                  				<td>{{ correlativo.numdocumentoasig }}</td>
											<td>{{ correlativo.fechadocumento }}</td>
											<td>{{ correlativo.correlativoact }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-correlativo bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'configuracion:correlativoedit' correlativo.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-correlativo bs-modal btn btn-sm btn-danger" data-form-url="{% url 'configuracion:correlativodelete' correlativo.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-correlativo").modalForm({
				formURL: "{% url 'configuracion:correlativocreate' %}"
			});

			var table = $("#correlativo-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#user-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-correlativo").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-correlativo").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}

templates/configuracion/empresalist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Empresas</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Empresas en el Sistema SnackCash&reg</h3>
						<button id="create-empresa" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Empresa</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="empresa-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Logo</th>
	                  				<th>Empresa</th>
	                  				<th>Inicio Licencia</th>
	                  				<th>Fin Licencia</th>
									<th>Acerca</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for empresa in object_list %}
			                			<tr class="gradeU">
											<td>{{ empresa.id }}</td>
											<td><img src="../../static/uploads/{{ empresa.logo }}" width="60" height="60"></td>
			                  				<td>{{ empresa.nombre }}</td>		                  				
			                  				<td>{{ empresa.fechaini }}</td>
			                  				<td>{{ empresa.fechafin }}</td>
											<td>{{ empresa.about }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-empresa bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'configuracion:empresaedit' empresa.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-empresa bs-modal btn btn-sm btn-danger" data-form-url="{% url 'configuracion:empresadelete' empresa.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-empresa").modalForm({
				formURL: "{% url 'configuracion:empresacreate' %}"
			});

			var table = $("#empresa-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#empresa-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-empresa").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-empresa").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}