apps/inventario/urls.py
from django.urls import include, path
from django.contrib.auth.decorators import login_required
from .views import CategoriaList, CategoriaCreate, CategoriaUpdate, CategoriaDelete, ProductoList, \
    ProductoCreate, ProductoUpdate, ProductoDelete , EspecialeList, EspecialeCreate, \
    EspecialeUpdate, EspecialeDelete, InventarioList, InventarioCreate, \
    InventarioUpdate, InventarioDelete, procesar_csv

app_name = 'inventario'

urlpatterns = [
    path('procesar-csv/', procesar_csv, name='procesar_csv'),
    
    path('categorias/', login_required(CategoriaList.as_view()), name='categorialist'),
    path('categorias/create/', login_required(CategoriaCreate.as_view()), name='categoriacreate'),
    path('categorias/edit/<int:pk>/', login_required(CategoriaUpdate.as_view()), name='categoriaedit'),
    path('categorias/delete/<int:pk>/', login_required(CategoriaDelete.as_view()), name='categoriadelete'),
    
    path('productos/', login_required(ProductoList.as_view()), name='productolist'),
    path('productos/create/', login_required(ProductoCreate.as_view()), name='productocreate'),
    path('productos/edit/<int:pk>/', login_required(ProductoUpdate.as_view()), name='productoedit'),
    path('productos/delete/<int:pk>/', login_required(ProductoDelete.as_view()), name='productodelete'),
    
    path('especiales/', login_required(EspecialeList.as_view()), name='especialelist'),
    path('especiales/create/', login_required(EspecialeCreate.as_view()), name='especialecreate'),
    path('especiales/edit/<int:pk>/', login_required(EspecialeUpdate.as_view()), name='especialeedit'),
    path('especiales/delete/<int:pk>/', login_required(EspecialeDelete.as_view()), name='especialedelete'),
    
    path('inventarios/', login_required(InventarioList.as_view()), name='inventariolist'),
    path('inventarios/create/', login_required(InventarioCreate.as_view()), name='inventariocreate'),
    path('inventarios/edit/<int:pk>/', login_required(InventarioUpdate.as_view()), name='inventarioedit'),
    path('inventarios/delete/<int:pk>/', login_required(InventarioDelete.as_view()), name='inventariodelete'),
	
 
]

inventory/urls.py
from django.contrib import admin
from django.urls import path, include

from django.contrib.auth.views import LoginView, logout_then_login

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/login/', LoginView.as_view(template_name='login.html'), name = 'login'),
    path('logout', logout_then_login, name = 'logout'),
    path('configuracion/', include('apps.configuracion.urls', namespace = 'configuracion')),
    path('inventario/', include('apps.inventario.urls', namespace = 'inventario')),
    path('compra/', include('apps.compra.urls', namespace = 'compra')),
    path('venta/', include('apps.venta.urls', namespace = 'venta')),
    path('usuario/', include('apps.usuario.urls', namespace = 'usuario')),
]

apps/inventario/forms.py
# forms.py
from django import forms
from django.apps import apps
from .models import Categoria, Producto, Especiale, Inventario
from bootstrap_modal_forms.forms import BSModalModelForm

class CategoriaForm(BSModalModelForm):
    class Meta:
        model = Categoria
        fields = [
			'nombre',
			'descripcion',
		]
        labels = {
   
			'nombre' : 'Nombre de Categoría',
			'descripcion' : 'Descripción Categoría',
        }
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Categoría'}),
            'descripcion': forms.TextInput(attrs={'class':'form-control','placeholder': 'Descripcion Categoría'}),
        }
        
class ProductoForm(BSModalModelForm):
    class Meta:
        model = Producto
        fields = [
            'categoria',
			'codigo',
			'nombre',
            'descripcion',
            'photo',
            'contenedor',
            'cantidadcontenedor',
            
		]
        labels = {
            'categoria' : 'Nombre Categoría',
			'codigo' : 'Codigo Producto',
			'nombre' : 'Nombre Producto',
            'descripcion' : 'Descripción Producto',
            'photo' : 'Foto Producto',
            'contenedor' : 'Contenedor Producto',
            'cantidadcontenedor' : 'Cantidad Contenedor',
        }
        widgets = {
            'categoria': forms.ModelChoiceField(queryset=Categoria.objects.all()),
			'codigo' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Codigo Producto'}),
			'nombre' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Producto'}),
            'descripcion' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Descripción Producto'}),
            'photo' : forms.ClearableFileInput(attrs={'class':'form-control', 'placeholder': 'Seleccione Imagen Producto'}),
            'contenedor' : forms.Select(attrs={'class':'form-control'}),
            'cantidadcontenedor' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Cantidad Contenedor'}),
        }
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Filtrar las opciones del campo 'categoria' solo para las categorías de productos
        self.fields['categoria'].queryset = Categoria.objects.filter(producto__isnull=False).distinct()
        
class EspecialeForm(BSModalModelForm):
    class Meta:
        model = Especiale
        fields = [
			'producto',
			'cantidad',
            'precio',
		]
        labels = {
            'producto' : 'Nombre de Producto',
			'cantidad' : 'Cantidad Producto',
            'precio' : 'Precio Producto',
        }
        widgets = {
            'producto': forms.Select(attrs={'class':'form-control','placeholder': 'Nombre Categoría'}),
			'cantidad': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Categoría'}),
            'precio': forms.TextInput(attrs={'class':'form-control','placeholder': 'Nombre Categoría'}),
        }
        
class InventarioForm(BSModalModelForm):
    class Meta:
        model = Inventario
        fields = [
            'sucursal',
			'producto',
			'stock',
            'stockminimo',
            'stockmaximo',
            'preciocompra',
            'utilidad',
            'iva',
            'precioventa',
		]
        labels = {
            'sucursal' : 'Nombre Sucursal',
			'producto' : 'Nombre Producto',
			'stock' : 'Stock',
            'stockminimo' : 'Stock Minimo',
            'stockmaximo' : 'Stock Maximo',
            'preciocompra' : 'Precio Compra',
            'utilidad' : 'Utilidad',
            'iva' : 'IVA',
            'precioventa' : 'Precio Venta',
        }
        widgets = {
            'sucursal' : forms.Select(attrs={'class':'form-control'}),
			'producto' : forms.Select(attrs={'class':'form-control'}),
			'stock' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Stock Producto'}),
            'stockminimo' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Stock Minimo Producto'}),
            'stockmaximo' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Stock Maximo Producto'}),
            'preciocompra' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Precio Compra'}),
            'utilidad' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Utilidad'}),
            'iva' : forms.TextInput(attrs={'class':'form-control','placeholder': 'IVA'}),
            'precioventa' : forms.TextInput(attrs={'class':'form-control','placeholder': 'Precio Venta'}),
        }
        
class CsvProcessorForm(forms.Form):
    modelos_inventario = [(model.__name__, model.__name__) for model in apps.get_app_config('inventario').get_models()]
    modelo = forms.ChoiceField(choices=modelos_inventario, label='Selecciona el modelo')
    archivo = forms.FileField(label='Selecciona el Archivo CSV')
    progreso = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
        

apps/inventario/views.py
from django.shortcuts import render, redirect
from django.views.generic import ListView
from .models import Categoria, Producto, Especiale, Inventario
from .forms import CategoriaForm, ProductoForm, EspecialeForm, InventarioForm, CsvProcessorForm
from bootstrap_modal_forms.generic import BSModalCreateView, BSModalUpdateView, BSModalReadView, BSModalDeleteView
from django.urls import reverse_lazy, reverse
from .csv_processor import CsvProcessor
from django.apps import apps  
from django.http import JsonResponse, HttpResponseServerError, HttpResponseRedirect
from django.contrib import messages
from django import forms
import logging

# Create your views here.

class CategoriaList(ListView):
    model = Categoria
    template_name = 'inventario/categorialist.html'

class CategoriaCreate(BSModalCreateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'inventario/categoriaadd.html'
    success_message = 'Hecho! Categoría Creada Correctamente.'
    success_url = reverse_lazy('inventario:categorialist')

class CategoriaUpdate(BSModalUpdateView):
    model = Categoria
    form_class = CategoriaForm
    template_name = 'inventario/categoriaedit.html'
    success_message = 'Hecho! Categoría Actualizada Correctamente.'
    success_url = reverse_lazy('inventario:categorialist')

class CategoriaDelete(BSModalDeleteView):
    model = Categoria
    template_name = 'inventario/categoriadelete.html'
    success_message = 'Hecho! Categoría Eliminada Correctamente.'
    success_url = reverse_lazy('inventario:categorialist')
    
###################################################################################################

class ProductoList(ListView):
    model = Producto
    template_name = 'inventario/productolist.html'

class ProductoCreate(BSModalCreateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'inventario/productoadd.html'
    success_message = 'Hecho! Producto Creado Correctamente.'
    success_url = reverse_lazy('inventario:productolist')

class ProductoUpdate(BSModalUpdateView):
    model = Producto
    form_class = ProductoForm
    template_name = 'inventario/productoedit.html'
    success_message = 'Hecho! Producto Actualizado Correctamente.'
    success_url = reverse_lazy('inventario:productolist')

class ProductoDelete(BSModalDeleteView):
    model = Producto
    template_name = 'inventario/productodelete.html'
    success_message = 'Hecho! Producto Eliminado Correctamente.'
    success_url = reverse_lazy('inventario:productolist')
    
################################################################################################

class EspecialeList(ListView):
    model = Especiale
    template_name = 'inventario/especialelist.html'

class EspecialeCreate(BSModalCreateView):
    model = Especiale
    form_class = EspecialeForm
    template_name = 'inventario/especialeadd.html'
    success_message = 'Hecho! Producto Especial Creado Correctamente.'
    success_url = reverse_lazy('inventario:especialelist')

class EspecialeUpdate(BSModalUpdateView):
    model = Especiale
    form_class = EspecialeForm
    template_name = 'inventario/especialeedit.html'
    success_message = 'Hecho! Producto Especial Actualizado Correctamente.'
    success_url = reverse_lazy('inventario:especialelist')

class EspecialeDelete(BSModalDeleteView):
    model = Especiale
    template_name = 'inventario/especialedelete.html'
    success_message = 'Hecho! Producto Especial Eliminado Correctamente.'
    success_url = reverse_lazy('inventario:especialelist')
    
################################################################################################

class InventarioList(ListView):
    model = Inventario
    template_name = 'inventario/inventariolist.html'

class InventarioCreate(BSModalCreateView):
    model = Inventario
    form_class = InventarioForm
    template_name = 'inventario/inventarioadd.html'
    success_message = 'Hecho! Producto Agregado al Inventario Correctamente.'
    success_url = reverse_lazy('inventario:inventariolist')

class InventarioUpdate(BSModalUpdateView):
    model = Inventario
    form_class = InventarioForm
    template_name = 'inventario/inventarioedit.html'
    success_message = 'Hecho! Producto Actualizado al Inventario Correctamente.'
    success_url = reverse_lazy('inventario:inventariolist')

class InventarioDelete(BSModalDeleteView):
    model = Inventario
    template_name = 'inventario/inventariodelete.html'
    success_message = 'Hecho! Producto Eliminado del Inventario Correctamente.'
    success_url = reverse_lazy('inventario:inventariolist')
    
#################################################################################################

def procesar_csv(request):
    try:
        if request.method == 'POST':
            form = CsvProcessorForm(request.POST, request.FILES)
            if form.is_valid():
                modelo_nombre = form.cleaned_data['modelo']
                modelo = apps.get_model('inventario', modelo_nombre)

                archivo = request.FILES['archivo']

                # Definir el mapeo de campos según el modelo seleccionado
                if modelo == Categoria:
                    field_mapping = {
                        'nombre': 'nombre',
                        'descripcion': 'descripcion',
                    }
                elif modelo == Producto:
                    field_mapping = {
                        'codigo': 'codigo',
                        'nombre': 'nombre',
                        'descripcion': 'descripcion',
                        'photo': 'photo',
                        'contenedor': 'contenedor',
                        'cantidadcontenedor': 'cantidadcontenedor',
                        'categoria_id': 'categoria_id',
                    }
                else:
                    # Agrega mapeos para otros modelos según sea necesario
                    field_mapping = {}

                csv_processor = CsvProcessor(model=modelo, csv_file=archivo, field_mapping=field_mapping)
                progreso = list(csv_processor.process_csv())

                # Agregar un mensaje de éxito
                messages.success(request, 'CSV procesado con éxito.')

            # Redirigir a la URL correspondiente
            if modelo == Categoria:
                return redirect('inventario:categorialist')
            elif modelo == Producto:
                return redirect('inventario:productolist')

    except Exception as e:
        # Capturar y registrar la excepción
        messages.error(request, f'Error al procesar el CSV: {str(e)}')
        return HttpResponseServerError()

    return render(request, 'inventario/procesarcsv.html', {'form': CsvProcessorForm()})

templates/inventario/categoriaadd.html
<form method="post" action="" enctype="multipart/form-data">
    {% csrf_token %}
  
    <div class="modal-header">
        <h5 class="modal-title">Crear Nueva Categoría</h5> 
        <button type="button" class="close pull-right" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      
    </div>
  
    <div class="modal-body">
      {% for field in form %}
        <div class="form-group{% if field.errors %} invalid{% endif %}">
          <label for="{{ field.id_for_label }}">{{ field.label }}</label>
          {{ field }}
          {% for error in field.errors %}
            <p class="help-block">{{ error }}</p>
          {% endfor %}
        </div>
      {% endfor %}
    </div>
  
    <div class="modal-footer">
      <button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      <button type="submit" class="btn btn-primary">Crear</button>
    </div>
  
</form>

templates/inventario/categoriadelete.html
<form method="post" class="form-horizontal">
	{% csrf_token %}

	<div class="modal-header">
		<h3 class="modal-title">Eliminar Categoría</h3>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close">
		  <span aria-hidden="true">&times;</span>
		</button>
	  </div>
	
	  <div class="modal-body">
		<p>Desea Eliminar el Registro de 
		  <strong>{{ object.nombre }} </br> {{ object.last_name }}</strong>?</p>
	  </div>
	
	  <div class="modal-footer">
		<button type="submit" class="btn btn-danger">Eliminar</button>
		<button type="button" class="btn btn-secondary" data-dismiss="modal">Cerrar</button>
	  </div>

</form>	          			            		
	          		

templates/inventario/categorialist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Categorías</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Categorias para Productos en el Sistema SnackCash&reg</h3>
						<button id="create-categoria" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Categoria</button>
						<button id="importcsv" class="btn btn-sm btn-secondary float-right" type="button" name="button"><i class="fa fa-download"></i> Importar Categorias</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="categoria-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Nombre</th>
	                  				<th>Descripción</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for categoria in object_list %}
			                			<tr class="gradeU">
											<td>{{ categoria.id }}</td>
			                  				<td>{{ categoria.nombre }}</td>
											<td>{{ categoria.descripcion }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-categoria bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'inventario:categoriaedit' categoria.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-categoria bs-modal btn btn-sm btn-danger" data-form-url="{% url 'inventario:categoriadelete' categoria.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-categoria").modalForm({
				formURL: "{% url 'inventario:categoriacreate' %}"
			});
			$("#importcsv").modalForm({
				formURL: "{% url 'inventario:procesar_csv' %}"
			});

			var table = $("#categoria-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#categoria-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-categoria").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-categoria").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}

templates/inventario/especialelist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Productos Especiales (Promociones)</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Productos Especiales en el Sistema SnackCash&reg</h3>
						<button id="create-especiale" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Producto Especial</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="especiale-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Producto</th>
									<th>Cantidad</th>
									<th>Precio</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for especiale in object_list %}
			                			<tr class="gradeU">
											<td>{{ especiale.id }}</td>
			                  				<td>{{ especiale.producto }}</td>
											<td>{{ especiale.cantidad }}</td>
											<td>{{ produespecialecto.precio }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-especiale bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'inventario:especialeedit' especiale.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-especiale bs-modal btn btn-sm btn-danger" data-form-url="{% url 'inventario:especialedelete' especiale.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-especiale").modalForm({
				formURL: "{% url 'inventario:especialecreate' %}"
			});

			var table = $("#especiale-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#especiale-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-especiale").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-especiale").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}

templates/inventario/productolist.html
{% extends 'base/base.html' %}
{% load static %}

{% block content %}
<section class="content-header">
	<div class="container-fluid">
	  <div class="row mb-2">
		<div class="col-sm-6">
		  <h1>Productos</h1>
		</div>
	  </div>
	</div><!-- /.container-fluid -->
</section>
<section class="content">
	<div class="container-fluid">
		<div class="row">
	      	<div class="col-12">
				<div class="card">
					<div class="card-header">
						<h3 class="card-title">Listado de Productos en el Sistema SnackCash&reg</h3>
						<button id="create-producto" class="btn btn-sm btn-success float-right" type="button" name="button"><i class="fa fa-plus"></i> Crear Producto</button>
						<button id="importcsv" class="btn btn-sm btn-secondary float-right" type="button" name="button"><i class="fa fa-download"></i> Importar Productos</button>
					</div>	          		
	          		<div class="card-body">
	            		<table id="producto-table" class="table table-bordered table-striped">
	              			<thead>
	                			<tr>
									<th>Id</th>
									<th>Barras</th>
									<th>Foto</th>
									<th>Codigo</th>
	                  				<th>Nombre</th>
									<th>Descripción</th>									
									<th>Contenedor</th>
									<th>Cant. Conte.</th>
									<th>Categoría</th>
	                  				<th>Acciones</th>
	                			</tr>
	              			</thead>
	              			<tbody>
	              				{% if object_list %}
		              				{% for producto in object_list %}
			                			<tr class="gradeU">																						
											<td>{{ producto.id }}</td>
											<td>
												{% if producto.codigo %}
													{% with codigo_barras=producto.generar_codigo_barras %}
														{% if codigo_barras %}
															<img src="{% static codigo_barras %}" alt="{{ producto.codigo }}" />
														{% endif %}
													{% endwith %}
												{% endif %}
											</td>
											<td>
												{% if producto.photo %}
													<img src="{% static 'uploads/' %}{{ producto.photo }}" width="60" height="60">
												{% else %}
													<img src="{% static 'uploads/productos/imagen-no-disponible.png' %}" width="60" height="60"></td>
												{% endif %}
											</td>
			                  				<td>{{ producto.codigo }}</td>
											<td>{{ producto.nombre }}</td>
											<td>{{ producto.descripcion }}</td>
			                  				<td>{{ producto.contenedor }}</td>
											<td>{{ producto.cantidadcontenedor }}</td>
											<td>{{ producto.categoria }}</td>
			                  				<td>			                  					
												<button type="button" class="edit-producto bs-modal btn btn-sm btn-secondary" data-form-url="{% url 'inventario:productoedit' producto.id %}">
													<span class="fa fa-user-edit"></span>
												</button>			                  					
												<button type="button" class="delete-producto bs-modal btn btn-sm btn-danger" data-form-url="{% url 'inventario:productodelete' producto.id %}">
													<span class="fa fa-trash"></span>
												</button>
			                  				</td>
			                			</tr>
		                			{% endfor %}
		                		{% endif %}
	              			</tbody>
	            		</table>
	          		</div>
	        	</div>
	        </div>
	    </div>
	</div>
</section>
<!--end-main-container-part-->
{% endblock %}

{% block scriptbottom %}

	<script type="text/javascript">
		
		// BS4
		$(document).ready(function() {
			$("#create-producto").modalForm({
				formURL: "{% url 'inventario:productocreate' %}"
			});
			$("#importcsv").modalForm({
				formURL: "{% url 'inventario:procesar_csv' %}"
			});

			var table = $("#producto-table").DataTable({
				language: {
					"decimal": "",
					"emptyTable": "No hay información",
					"info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
					"infoEmpty": "Mostrando 0 a 0 de 0 Entradas",
					"infoFiltered": "(Filtrado de _MAX_ total entradas)",
					"infoPostFix": "",
					"thousands": ",",
					"lengthMenu": "Mostrar _MENU_ Entradas",
					"loadingRecords": "Cargando...",
					"processing": "Procesando...",
					"search": "Buscar:",
					"zeroRecords": "Sin resultados encontrados",
					"paginate": {
						"first": "Primero",
						"last": "Ultimo",
						"next": "Siguiente",
						"previous": "Anterior"
					}
				},
				"ordering": true,
				"info": true,
				"responsive": true, 
				"lengthChange": true, 
				"autoWidth": true,
				"buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
			}).buttons().container().appendTo('#producto-table_wrapper .col-md-6:eq(0)');
		 
			new $.fn.dataTable.FixedHeader( table );
		});

		$(".edit-producto").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url")});
		});

		$(".delete-producto").each(function () {
			$(this).modalForm({formURL: $(this).data("form-url"), isDeleteForm: true});
		});
	
	</script>
		
{% endblock %}